### ISSUE TITLE
This is a really interesting application of AES-NI

### ISSUE THREAD

**Issue by noloader** [mjosaarinen/sm4ni#2]
No bug to report here... Just a hat's off for a really interesting application of AES-NI. I've seen it one other time with SHACAL2 and Intel's SHA instructions.

One small comment from the README:

> ARM is introducing special SM4 instructions in its future architectures.

ARM already released an updated architecture with SM4 support. It is part of ARMv8.4. Also see [Introducing 2017’s extensions to the Arm Architecture](https://community.arm.com/processors/b/blog/posts/introducing-2017s-extensions-to-the-arm-architecture). I have not seen any hardware yet. I understand there is QEMU support, however.

**Comment by jkivilin** [comment]
Very nice indeed. I just started to research on fast SM4 implementations, hit google with "sm4 aesni" and found my way here. This takes approach very similar to my AES-NI accelerated Camellia implementation, https://github.com/jkivilin/supercop-blockciphers/blob/beyond_master/crypto_stream/camellia128ctr/aesni-avx-16way/camellia_aesni.S

**Comment by noloader** [comment]
@jkivilin,

I'd be interested in a pull request for Camellia based on AES-NI at [weidai11 | cryptopp | camellia.cpp](https://github.com/weidai11/cryptopp/blob/master/camellia.cpp).

The PR would be most useful if it uses intrinsics. Intrinsics apply to Clang, GCC, ICC, SunCC and MSVC. GAS asm has limits, and SunCC and MSVC don't benefit.
