### ISSUE TITLE
Is this implementation secure?

### ISSUE THREAD

**Issue by amo1101** [mjosaarinen/sm4ni#4]
hi, i am seeking method to accelerate sm4 on armv8 CPU, your method is very interesting and i think it can be ported  to armv7 using aes crypto extension instruction instead of aes-ni.
but i wonder whether the method is secure? if it is, can u explain why?
thanks very much!

**Comment by mjosaarinen** [comment]
Well, it's constant-time, and voids potential cache timing attacks of table-based attacks. So it is more secure than the standard C implementation.
