### ISSUE TITLE
instresting implmentation 

### ISSUE THREAD

**Issue by xjtufjj** [mjosaarinen/sm4ni#6]
Seems IPP-crypto aslo using the same idea. 

BTW, in the ref code, you use the 32bit, in the sm4ni code, you use the xmm register. Are you sure the performance boost from aesni last round ? seems the vectorized code aslo can bring about 4x performance boost.

**Comment by mjosaarinen** [comment]
How is this an "issue" ?   The whole point is to vectorize -- which you can't do with an implementation that has S-Box table lookups.
